apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
spec:
  destination:
    namespace: defalut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sample/overlays/staging
    repoURL: git@github.com:tkkawa/twitter-manifests.git
    targetRevision: main
  syncPolicy:
    automated: {}